version: "3.3"

services:
  stp-exporter:
    image: stp-exporter:v1.0.0
    container_name: stp-exporter
    ports:
      - "8081:8081"
    environment:
      - URL=http://localhost:8080
      - DB=FKU_raspred
      - LOGIN=test
      - PASSWORD=test
      - AUTHORIZATION=cHVibGljX3JvX2NsaWVudDpAOVkjbmckXXU+SF4zajY=
    volumes:
      - ./config.yml:/config.yml
    restart: always
    network_mode: "host"
